### ISSUE TITLE
Authorization token needs to be in bearer as of 7.4.5(?)

### ISSUE THREAD

**Issue by wintermute000** [mcarneir0/fortigate-backup-api#1]
The script no longer works at least as of a new FGT on 7.4.5.

This is broken

curl -k -i https://xxx/api/v2/monitor/system/config/backup?scope=global&access_token=xxxxxx

The token needs to be in the bearer now, at least for new VMs/new API users.

curl -k -H "Authorization: Bearer xxxx" https://xxx/api/v2/monitor/system/config/backup?scope=global

Note: existing FGT/users seem unaffected.

**Comment by mcarneir0** [comment]
Sorry for late reply, i no longer have access to Fortigates because i did this at my previous job. Maybe it's possible for me to continue development using Fortigate VM.

Thanks for reporting this anyway.

**Comment by wintermute000** [comment]
No problem, I forked it and fixed it.
I probably should have submitted a pull request, but I fixed it on the main branch
________________________________

**Comment by mcarneir0** [comment]
Thanks for helping keep this project updated with the latest versions of Fortigate, i will merge them soon when i have some free time

**Comment by wintermute000** [comment]
no worries, the fix is trivial - put the auth in the header, and change to POST
________________________________

**Comment by wintermute000** [comment]
There's a second fix - maybe I didn't commit my local changes - but all it is is setting the GET to POST
________________________________

**Comment by mcarneir0** [comment]
> There's a second fix - maybe I didn't commit my local changes - but all it is is setting the GET to POST

Would you like to push these changes?

**Comment by wintermute000** [comment]
I pushed it to my repo – sorry but I’m not clear on how to push to yours (if that’s what you’re asking)?

**Comment by mcarneir0** [comment]
Merged, thank you @wintermute000
